name: Update readme

on:
  schedule:
    - cron: "0 1 * * *"
  workflow_dispatch:

  # 마스터 Branch의 모든 push 실행
  push:
    branches:
    - master

jobs:
  readme:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: 20 #14
      - run: npm install

      - name: Generate readme
        env:
          WEATHER_API_KEY: ${{ secrets.WEATHER_API_KEY }}
        run: node build-svg.js

      - name: Commit changes
        uses: EndBug/add-and-commit@v4
        with:
          author_name: JOOHEE
          author_email: joohee6218@gmail.com
          message: "Auto updating my readme"
          add: "*.svg"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
